export const SET_NUMBER_OF_USERS = 'SET_NUMBER_OF_USERS';
export const SET_FETCH_USERS_LOADING = 'SET_FETCH_USERS_LOADING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
